/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kucharka.gui;


import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kucharka.model.Recipe;

/**
 *
 * @author Michael
 */
public class RecipesFrm extends javax.swing.JFrame {
    Recipe recept = null;
    /**
     * Creates new form RecipesFrm
     */
    public RecipesFrm() {
     //   scrollPane.getVerticalScrollBar().setEnabled(false);
        setPreferredSize(new Dimension(565,500));
        setLocation(new Point(500,0));
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(zavirani);
        setResizable(false);
      //  pack();
      //    tabbedPane.addTab(recept.getName(), new TabRecipe(recept));
      //  setVisible(true);
        
    }
    WindowAdapter zavirani = new WindowAdapter() {

        @Override
        public void windowClosing(WindowEvent e) {
            
            int res = JOptionPane.showConfirmDialog(null, "YES==close window || NO== KONEC aplikace ", "Close or dispose?", JOptionPane.YES_NO_CANCEL_OPTION);
            if ( res == 0 ) {
                // dispose method issues the WINDOW_CLOSED event
                setVisible(false);
            } else if(res == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                dispose();
            }
            
        }
        
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane.setViewportView(tabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    public javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
