/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kucharka.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import kucharka.model.Recipe;

/**
 *
 * @author Michael
 */
public class TabRecipe extends javax.swing.JPanel {
     Recipe recept = null;
    String name = null;
    Image img = null;
    
    private void nacteniImg(final URL adresa){
        try {
            img = ImageIO.read(adresa);
        } catch (IOException ex) {
            Logger.getLogger(TabRecipe.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }
    private ImageIcon vratIcon(Image img){
    ImageIcon icon = new ImageIcon(this.recept.getObrazek());
        return icon;
    }
    public TabRecipe(Recipe recept) {
        initComponents();
     
            this.recept = recept;
            this.name = recept.getName();
            initTab(recept);
       
    }
    private void setSuroviny(List<String> suroviny){
        
        for (String surovina : suroviny) {
            //výraz který odstraní nežádané hodnoty např &frac12;  který jsem objevil ve výpisu
            if (surovina.charAt(0) != "&".toCharArray()[0]) {
            this.suroviny.setText(this.suroviny.getText() +surovina + "\n"); //pridej surovinu to TextArey a odradkuj
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        recipeProgres2 = new javax.swing.JTextArea();
        label2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recipeID2 = new javax.swing.JLabel();
        jRecipeName2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        recipeCategory2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suroviny = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel4.setPreferredSize(new java.awt.Dimension(520, 419));

        recipeProgres2.setColumns(20);
        recipeProgres2.setRows(5);
        recipeProgres2.setAlignmentY(0.0F);
        recipeProgres2.setMargin(new java.awt.Insets(0, 2, 2, 2));
        jScrollPane3.setViewportView(recipeProgres2);

        label2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");
        jLabel1.setAlignmentY(0.0F);

        recipeID2.setText("nic");
        recipeID2.setAlignmentY(0.0F);

        jRecipeName2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRecipeName2.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kategorie:");
        jLabel2.setAlignmentY(0.0F);

        recipeCategory2.setText("jLabel3");
        recipeCategory2.setAlignmentY(0.0F);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Postup");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        suroviny.setColumns(20);
        suroviny.setRows(5);
        jScrollPane1.setViewportView(suroviny);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingredience");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(recipeID2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(recipeCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addComponent(jRecipeName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jRecipeName2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recipeID2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recipeCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jRecipeName2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel label2;
    private javax.swing.JLabel recipeCategory2;
    private javax.swing.JLabel recipeID2;
    private javax.swing.JTextArea recipeProgres2;
    private javax.swing.JTextArea suroviny;
    // End of variables declaration//GEN-END:variables

    private void initTab(final Recipe recept) {
                       
        setSuroviny(recept.getIngredience());
        jRecipeName2.setText(recept.getName());
        recipeID2.setText(recept.getId());
        recipeCategory2.setText(recept.getCategory());
        recipeProgres2.setLineWrap(true); //nejdulezitejsi radky pro Jscroll pane
        recipeProgres2.setWrapStyleWord(true);
        suroviny.setLineWrap(true);
        suroviny.setWrapStyleWord(true);
        recipeProgres2.setText(recept.getProcess());
        recipeProgres2.setSelectedTextColor(Color.GREEN);//zeleny vyber
        suroviny.setSelectedTextColor(Color.GREEN);//zeleny vyber
        recipeProgres2.setCaretPosition(0);
        suroviny.setCaretPosition(0);       

        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                if (recept.getObrazek() != null) {                   
                nacteniImg(recept.getObrazek());
                jLabel5.setIcon(vratIcon(img));                   
                } else {
                    jLabel5.setPreferredSize(new Dimension(100,30));
                    
                    jLabel5.setText("Obrázek neexistuje!");
                }
            }
        });
                            

                            
                
                        
                   

        
    //   initObrazek.start();
       

        
//        jLabel5.addMouseListener(new MouseAdapter() {
//            
//        @Override
//        public void mousePressed(MouseEvent e) {
//            jLabel1.setVisible(false);
//            jLabel2.setVisible(false); 
//            jLabel3.setVisible(false);
//            jLabel4.setVisible(false);
//            jRecipeName2.setVisible(false);
//            jScrollPane1.setVisible(false);
//            jScrollPane3.setVisible(false);
//            recipeID2.setVisible(false);
//            recipeCategory2.setVisible(false);
//            
//            
//           // jLabel5.setIcon(vratIcon(nacteniImg(recept.getObrazek())));
////            if (jLabel5.getSize().equals(new Dimension(320,200))) {
////                jScrollPane1.setVisible(true);
////                jScrollPane3.setVisible(true);
////                jLabel4.setVisible(true);
////                jLabel5.setSize(new Dimension(50,50));
////            } else {
////                
////                jLabel5.setSize(320, 200);
////                jLabel4.setVisible(false);
////               
////                jScrollPane1.setVisible(false);
////                jScrollPane3.setVisible(false);
////               
////        
////            }
//            
//        }
//    });
        suroviny.setEditable(false);
        recipeProgres2.setEditable(false);
    }
    Thread initObrazek = new Thread(){

        @Override
        public synchronized void start() {
            if (initObrazek instanceof Runnable) {
            super.start();
            }
        }
        
                @Override
                public void run() {
                      nacteniImg(recept.getObrazek());
                      
                        
                }
                    
                };
   
}
